version: "3.7"

services:

      
  database_nestlotery:
    image: postgres
    container_name: database_nestlotery
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=lotery
      - POSTGRES_PASSWORD=lotery
      - POSTGRES_DB=lotery
    volumes: 
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
